export const ADD_CHALLENGESTAT = 'ADD_CHALLENGESTAT';
export const DELETE_CHALLENGESTAT = 'DELETE_CHALLENGESTAT';
export const UPDATE_CHALLENGESTAT = 'UPDATE_CHALLENGESTAT';

export const FETCH_CHALLENGESTAT_REQUEST = 'FETCH_CHALLENGESTAT_REQUEST'
export const FETCH_CHALLENGESTAT_SUCCESS = 'FETCH_CHALLENGESTAT_SUCCESS'
export const FETCH_CHALLENGESTAT_FAILURE = 'FETCH_CHALLENGESTAT_FAILURE'

export const FETCH_TOPCHALLENGESTATS_REQUEST = 'FETCH_TOPCHALLENGESTATS_REQUEST'
export const FETCH_TOPCHALLENGESTATS_SUCCESS = 'FETCH_TOPCHALLENGESTATS_SUCCESS'
export const FETCH_TOPCHALLENGESTATS_FAILURE = 'FETCH_TOPCHALLENGESTATS_FAILURE'
